/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.engcia;

import org.engcia.model.Evidence;
import org.engcia.model.Hypothesis;
import org.engcia.model.Conclusion;
import org.engcia.model.Fact;

import function org.engcia.view.UI.answer;

query "Conclusions"
	$conclusion : Conclusion()
end

// -----------------------------   1 - Hide and Seek

rule "hns1"
	when
		eval(answer(Evidence.ORIG_PKTS, ">", 11))
	then
		Conclusion c = new Conclusion(Conclusion.HIDE_AND_SEEK, 100.00);
		insert(c);
end

rule "hns2"
	when
		eval(answer(Evidence.ORIG_PKTS, "<=", 11))
		eval(answer(Evidence.RESP_PKTS, ">", 2))
	then
		Conclusion c = new Conclusion(Conclusion.HIDE_AND_SEEK, 15.43);
		insert(c);
end

rule "hns3"
	when
		eval(answer(Evidence.ORIG_PKTS, "<=", 11))
		eval(answer(Evidence.RESP_PKTS, "<=", 2))
		eval(answer(Evidence.CONN_STATE, "S2"))
	then
		Conclusion c = new Conclusion(Conclusion.HIDE_AND_SEEK, 13.69);
		insert(c);
end

rule "hns4"
	when
		eval(answer(Evidence.ORIG_PKTS, "<=", 11))
		eval(answer(Evidence.RESP_PKTS, "<=", 2))
		not(eval(answer(Evidence.CONN_STATE, "S2")))
		eval(answer(Evidence.HISTORY, ">", 38))
	then
		Conclusion c = new Conclusion(Conclusion.HIDE_AND_SEEK, 1.27);
		insert(c);
end

rule "hns5"
	when
		eval(answer(Evidence.ORIG_PKTS, "<=", 11))
		eval(answer(Evidence.RESP_PKTS, "<=", 2))
		not(eval(answer(Evidence.CONN_STATE, "S2")))
		eval(answer(Evidence.HISTORY, "<=", 38))
	then
		Conclusion c = new Conclusion(Conclusion.HIDE_AND_SEEK, 0);
		insert(c);
end

// -----------------------------   3 - MUHSTIK

rule "mtk1"
	when
		eval(answer(Evidence.ID_RESP_P, ">", 1265))
	then
		Conclusion c = new Conclusion(Conclusion.MUHSTIK, 99.73);
        insert(c);
end

rule "mtk2"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 1265))
		eval(answer(Evidence.ORIG_BYTES, ">", 1172))
		eval(answer(Evidence.ORIG_PKTS, "<=", 19))
	then
		Conclusion c = new Conclusion(Conclusion.MUHSTIK,40.05);
        insert(c);
end

rule "mtk3"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 1265))
		eval(answer(Evidence.ORIG_BYTES, ">", 1172))
		eval(answer(Evidence.ORIG_PKTS, ">", 19))
		eval(answer(Evidence.ORIG_BYTES, "<=", 1866))
	then
		Conclusion c = new Conclusion(Conclusion.MUHSTIK, 20.49);
        insert(c);
end

rule "mtk4"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 1265))
		eval(answer(Evidence.ORIG_PKTS, ">", 19))
		eval(answer(Evidence.ORIG_BYTES, ">", 1866))
	then
		Conclusion c = new Conclusion(Conclusion.MUHSTIK, 0.00);
        insert(c);
end

rule "mtk5"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 1265))
		eval(answer(Evidence.ORIG_BYTES, "<=", 1172))
		eval(answer(Evidence.ORIG_PKTS, ">", 18))
		eval(answer(Evidence.ORIG_BYTES, ">", 487))
		eval(answer(Evidence.RESP_PKTS, ">", 12))
	then
		Conclusion c = new Conclusion(Conclusion.MUHSTIK, 0.00);
        insert(c);
end

rule "mtk6"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 1265))
		eval(answer(Evidence.ORIG_BYTES, "<=", 1172))
		eval(answer(Evidence.ORIG_PKTS, ">", 18))
		eval(answer(Evidence.ORIG_BYTES, ">", 487))
		eval(answer(Evidence.RESP_PKTS, "<=", 12))
	then
		Conclusion c = new Conclusion(Conclusion.MUHSTIK, 9.23);
        insert(c);
end

rule "mtk7"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 1265))
		eval(answer(Evidence.ORIG_PKTS, ">", 18))
		eval(answer(Evidence.ORIG_BYTES, "<=", 487))
	then
		Conclusion c = new Conclusion(Conclusion.MUHSTIK, 14.11);
        insert(c);
end

rule "mtk8"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 1265))
		eval(answer(Evidence.ORIG_BYTES, "<=", 1172))
		eval(answer(Evidence.ORIG_PKTS, "<=", 18))
		eval(answer(Evidence.DURATION, ">", 4.9143))
	then
		Conclusion c = new Conclusion(Conclusion.MUHSTIK, 0.48);
        insert(c);
end

rule "mtk9"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 1265))
		eval(answer(Evidence.ORIG_BYTES, "<=", 1172))
		eval(answer(Evidence.ORIG_PKTS, "<=", 18))
		eval(answer(Evidence.DURATION, "<=", 4.9143))
	then
		Conclusion c = new Conclusion(Conclusion.MUHSTIK, 0.02);
        insert(c);
end

// -----------------------------   9 - HAJIME

rule "hjm1"
	when
		eval(answer(Evidence.RESP_PKTS, ">", 33))
	then
		Conclusion c = new Conclusion(Conclusion.HAJIME, 100.00);
        insert(c);
end

rule "hjm2"
	when
		eval(answer(Evidence.RESP_PKTS, "<=", 33))
		eval(answer(Evidence.RESP_PKTS, ">", 3))
		eval(answer(Evidence.ID_RESP_P, "<=", 22))
	then
		Conclusion c = new Conclusion(Conclusion.HAJIME, 91.66);
        insert(c);
end

rule "hjm3"
	when
		eval(answer(Evidence.RESP_PKTS, "<=", 33))
		eval(answer(Evidence.RESP_PKTS, ">", 3))
		eval(answer(Evidence.ID_RESP_P, ">", 22))
	then
		Conclusion c = new Conclusion(Conclusion.HAJIME, 0.03);
        insert(c);
end

rule "hjm4"
	when
		eval(answer(Evidence.RESP_PKTS, "<=", 33))
		eval(answer(Evidence.RESP_PKTS, "<=", 3))
		eval(answer(Evidence.CONN_STATE, "SF"))
	then
		Conclusion c = new Conclusion(Conclusion.HAJIME, 14.49);
        insert(c);
end

rule "hjm5"
	when
		eval(answer(Evidence.RESP_PKTS, "<=", 33))
		eval(answer(Evidence.RESP_PKTS, "<=", 3))
		not(eval(answer(Evidence.CONN_STATE, "SF")))
	then
		Conclusion c = new Conclusion(Conclusion.HAJIME, 0.00);
        insert(c);
end

// -----------------------------   17 - KENJIRO

rule "kjr1_1"
	when
		eval(answer(Evidence.ID_RESP_P, ">", 45042))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 29.60);
        insert(c);
end

rule "kjr1_2"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 45042))
		eval(answer(Evidence.SERVICE, "http"))
		eval(answer(Evidence.HISTORY, "<=", 8))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 69.26);
        insert(c);
end

rule "kjr1_3"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 45042))
		eval(answer(Evidence.SERVICE, "http"))
		eval(answer(Evidence.HISTORY, ">", 8))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 7.55);
        insert(c);
end

rule "kjr1_4"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 45042))
		not(eval(answer(Evidence.SERVICE, "http")))
		eval(answer(Evidence.ORIG_PKTS, ">", 30))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 18.98);
        insert(c);
end

rule "kjr1_5"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 45042))
		not(eval(answer(Evidence.SERVICE, "http")))
		eval(answer(Evidence.ORIG_PKTS, "<=", 30))
		eval(answer(Evidence.ORIG_IP_BYTES, "<=", 348))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 0.04);
        insert(c);
end

rule "kjr1_6"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 45042))
		not(eval(answer(Evidence.SERVICE, "http")))
		eval(answer(Evidence.ORIG_PKTS, "<=", 30))
		eval(answer(Evidence.ORIG_IP_BYTES, ">", 348))
		eval(answer(Evidence.HISTORY, ">", 4))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 31.02);
        insert(c);
end

rule "kjr1_7"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 45042))
		not(eval(answer(Evidence.SERVICE, "http")))
		eval(answer(Evidence.ORIG_PKTS, "<=", 30))
		eval(answer(Evidence.ORIG_IP_BYTES, ">", 348))
		eval(answer(Evidence.HISTORY, "<=", 4))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 0.72);
        insert(c);
end

// -----------------------------   20 - TORII

rule "tor2_1"
	when
		eval(answer(Evidence.CONN_STATE, "S1"))
	then
		Conclusion c = new Conclusion(Conclusion.TORII, 100.00);
        insert(c);
end

rule "tor2_2"
	when
		not(eval(answer(Evidence.CONN_STATE, "S1")))
		eval(answer(Evidence.ORIG_BYTES, "<=", 1761))
	then
		Conclusion c = new Conclusion(Conclusion.TORII, 0.00);
        insert(c);
end

rule "tor2_3"
	when
		not(eval(answer(Evidence.CONN_STATE, "S1")))
		eval(answer(Evidence.ORIG_BYTES, ">", 1761))
	then
		Conclusion c = new Conclusion(Conclusion.TORII, 43.75);
        insert(c);
end

// -----------------------------   21 - TORII

rule "tor1_1"
	when
		eval(answer(Evidence.ORIG_BYTES, "<=", 7975))
	then
		Conclusion c = new Conclusion(Conclusion.TORII, 0.00);
        insert(c);
end

rule "tor1_2"
	when
		eval(answer(Evidence.ORIG_BYTES, ">", 7975))
		eval(answer(Evidence.HISTORY, ">", 5))
	then
		Conclusion c = new Conclusion(Conclusion.TORII, 43.10);
        insert(c);
end

rule "tor1_3"
	when
		eval(answer(Evidence.ORIG_BYTES, ">", 7975))
		eval(answer(Evidence.HISTORY, "<=", 4))
	then
		Conclusion c = new Conclusion(Conclusion.TORII, 100.0);
        insert(c);
end

rule "tor1_4"
	when
		eval(answer(Evidence.ORIG_BYTES, ">", 7975))
		eval(answer(Evidence.HISTORY, "==", 5))
	then
		Conclusion c = new Conclusion(Conclusion.TORII, 74.78);
        insert(c);
end

// -----------------------------   33 - KENJIRO

rule "kjr2_1"
	when
		eval(answer(Evidence.ID_RESP_P, ">", 22648))
		eval(answer(Evidence.ID_ORIG_P, ">", 39624))
		eval(answer(Evidence.HISTORY, ">", 8))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 0.00);
        insert(c);
end

rule "kjr2_2"
	when
		eval(answer(Evidence.ID_RESP_P, ">", 22648))
		eval(answer(Evidence.ID_ORIG_P, ">", 39624))
		eval(answer(Evidence.HISTORY, "<=", 8))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 72.57);
        insert(c);
end

rule "kjr2_3"
	when
		eval(answer(Evidence.ID_RESP_P, ">", 22648))
		eval(answer(Evidence.ID_ORIG_P, "<=", 39624))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 85.50);
        insert(c);
end

rule "kjr2_4"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 22648))
		eval(answer(Evidence.ID_RESP_P, ">", 8080))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 11.16);
        insert(c);
end

rule "kjr2_5"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 8080))
		eval(answer(Evidence.ID_RESP_P, ">", 101))
		eval(answer(Evidence.ORIG_PKTS, ">", 4))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 33.33);
        insert(c);
end

rule "kjr2_6"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 8080))
		eval(answer(Evidence.ID_RESP_P, ">", 101))
		eval(answer(Evidence.ORIG_PKTS, "<=", 4))
		eval(answer(Evidence.ID_ORIG_P, ">", 44814))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 7.55);
        insert(c);
end

rule "kjr2_7"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 8080))
		eval(answer(Evidence.ID_RESP_P, ">", 101))
		eval(answer(Evidence.ORIG_PKTS, "<=", 4))
		eval(answer(Evidence.ID_ORIG_P, "<=", 44814))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 0.00);
        insert(c);
end

rule "kjr2_8"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 101))
		eval(answer(Evidence.CONN_STATE, "S0"))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 1.91);
        insert(c);
end

rule "kjr2_9"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 101))
		not(eval(answer(Evidence.CONN_STATE, "S0")))
	then
		Conclusion c = new Conclusion(Conclusion.KENJIRO, 0.00);
        insert(c);
end

// -----------------------------   34 - MIRAI

rule "mra5_1"
	when
		eval(answer(Evidence.ID_RESP_P, ">", 3461))
		eval(answer(Evidence.RESP_IP_BYTES, ">", 63))
		eval(answer(Evidence.RESP_PKTS, ">", 50))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 34.83);
        insert(c);
end

rule "mra5_2"
	when
		eval(answer(Evidence.ID_RESP_P, ">", 3461))
		eval(answer(Evidence.RESP_IP_BYTES, ">", 63))
		eval(answer(Evidence.RESP_PKTS, "<=", 50))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 0.04);
        insert(c);
end

rule "mra5_3"
	when
		eval(answer(Evidence.ID_RESP_P, ">", 3461))
		eval(answer(Evidence.RESP_IP_BYTES, "<=", 63))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 0.26);
        insert(c);
end

rule "mra5_4"
	when
		eval(answer(Evidence.ID_RESP_P, "<=", 3461))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 0.00);
        insert(c);
end

// -----------------------------   35 - MIRAI

rule "mra2_1"
	when
		eval(answer(Evidence.HISTORY, ">", 9))
		eval(answer(Evidence.ORIG_PKTS, ">", 68))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 25.00);
        insert(c);
end

rule "mra2_2"
	when
		eval(answer(Evidence.HISTORY, ">", 9))
		eval(answer(Evidence.ORIG_PKTS, "<=", 68))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 16.42);
        insert(c);
end

rule "mra2_3"
	when
		eval(answer(Evidence.HISTORY, "<=", 9))
		eval(answer(Evidence.ID_RESP_P, ">", 66))
		eval(answer(Evidence.DURATION, ">", 2.4132))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 1.12);
        insert(c);
end

rule "mra2_4"
	when
		eval(answer(Evidence.HISTORY, "<=", 9))
		eval(answer(Evidence.ID_RESP_P, ">", 66))
		eval(answer(Evidence.DURATION, "<=", 2.4132))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 0.64);
        insert(c);
end

rule "mra2_5"
	when
		eval(answer(Evidence.HISTORY, "<=", 9))
		eval(answer(Evidence.ID_RESP_P, "<=", 66))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 0.00);
        insert(c);
end

// -----------------------------   39 - IRCBOT

rule "irc1"
	when
		eval(answer(Evidence.ORIG_BYTES, "<=", 94))
	then
		Conclusion c = new Conclusion(Conclusion.IRCBOT, 0.00);
        insert(c);
end

rule "irc2"
	when
		eval(answer(Evidence.ORIG_BYTES, ">", 94))
		eval(answer(Evidence.ORIG_BYTES, ">", 114))
	then
		Conclusion c = new Conclusion(Conclusion.IRCBOT, 0.00);
        insert(c);
end

rule "irc3"
	when
		eval(answer(Evidence.ORIG_BYTES, ">", 94))
		eval(answer(Evidence.ORIG_BYTES, "<=", 114))
		eval(answer(Evidence.RESP_BYTES, ">", 49))
	then
		Conclusion c = new Conclusion(Conclusion.IRCBOT, 95.59);
        insert(c);
end

rule "irc4"
	when
		eval(answer(Evidence.ORIG_BYTES, ">", 94))
		eval(answer(Evidence.ORIG_BYTES, "<=", 114))
		eval(answer(Evidence.RESP_BYTES, "<=", 49))
	then
		Conclusion c = new Conclusion(Conclusion.IRCBOT, 0.00);
        insert(c);
end

// -----------------------------   42 - TROJAN

rule "trj1"
	when
		eval(answer(Evidence.MISSED_BYTES, ">", 730))
		eval(answer(Evidence.DURATION, ">", 1.0152))
	then
		Conclusion c = new Conclusion(Conclusion.TROJAN, 8.33);
        insert(c);
end

rule "trj2"
	when
		eval(answer(Evidence.MISSED_BYTES, ">", 730))
		eval(answer(Evidence.DURATION, "<=", 1.0152))
	then
		Conclusion c = new Conclusion(Conclusion.TROJAN, 53.74);
        insert(c);
end

rule "trj3"
	when
		eval(answer(Evidence.MISSED_BYTES, "<=", 730))
		eval(answer(Evidence.ORIG_PKTS, ">", 30))
	then
		Conclusion c = new Conclusion(Conclusion.TROJAN, 2.45);
        insert(c);
end

rule "trj4"
	when
		eval(answer(Evidence.MISSED_BYTES, "<=", 730))
		eval(answer(Evidence.ORIG_PKTS, "<=", 30))
	then
		Conclusion c = new Conclusion(Conclusion.TROJAN, 0.00);
        insert(c);
end

// -----------------------------   43 - MIRAI

rule "mra4_1"
	when
		eval(answer(Evidence.ID_ORIG_P, ">", 30647))
		eval(answer(Evidence.DURATION, ">", 4.1452))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 42.27);
		insert(c);
end

rule "mra4_2"
	when
		eval(answer(Evidence.ID_ORIG_P, ">", 30647))
		eval(answer(Evidence.DURATION, ">", 3.1616))
		eval(answer(Evidence.DURATION, "<=", 4.1452))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 95.57);
		insert(c);
end

rule "mra4_3"
	when
		eval(answer(Evidence.ID_ORIG_P, ">", 30647))
		eval(answer(Evidence.DURATION, "<=", 3.1616))
		not(eval(answer(Evidence.CONN_STATE, "RSTO")))
		not(eval(answer(Evidence.CONN_STATE, "S0")))
		eval(answer(Evidence.DURATION, ">", 1.0609))
		eval(answer(Evidence.HISTORY, ">", 6))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 23.63);
		insert(c);
end

rule "mra4_4"
	when
		eval(answer(Evidence.ID_ORIG_P, ">", 30647))
		eval(answer(Evidence.DURATION, "<=", 3.1616))
		not(eval(answer(Evidence.CONN_STATE, "RSTO")))
		not(eval(answer(Evidence.CONN_STATE, "S0")))
		eval(answer(Evidence.DURATION, ">", 1.0609))
		eval(answer(Evidence.HISTORY, "<=", 6))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 68.89);
		insert(c);
end

rule "mra4_5"
	when
		eval(answer(Evidence.ID_ORIG_P, ">", 30647))
		not(eval(answer(Evidence.CONN_STATE, "RSTO")))
		not(eval(answer(Evidence.CONN_STATE, "S0")))
		eval(answer(Evidence.DURATION, "<=", 1.0609))
		eval(answer(Evidence.ID_ORIG_P, ">", 36952))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 0.00);
		insert(c);
end

rule "mra4_6"
	when
		eval(answer(Evidence.ID_ORIG_P, ">", 30647))
		not(eval(answer(Evidence.CONN_STATE, "RSTO")))
		not(eval(answer(Evidence.CONN_STATE, "S0")))
		eval(answer(Evidence.DURATION, "<=", 1.0609))
		eval(answer(Evidence.ID_ORIG_P, "<=", 36952))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 23.24);
		insert(c);
end

rule "mra4_7"
	when
		eval(answer(Evidence.ID_ORIG_P, ">", 30647))
		eval(answer(Evidence.DURATION, "<=", 3.1616))
		eval(answer(Evidence.CONN_STATE, "RSTO"))
		eval(answer(Evidence.ORIG_BYTES, ">", 19))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 90.25);
		insert(c);
end

rule "mra4_8"
	when
		eval(answer(Evidence.ID_ORIG_P, ">", 30647))
		eval(answer(Evidence.DURATION, "<=", 3.1616))
		eval(answer(Evidence.CONN_STATE, "S0"))
		eval(answer(Evidence.ORIG_BYTES, ">", 19))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 90.25);
		insert(c);
end

rule "mra4_9"
	when
		eval(answer(Evidence.ID_ORIG_P, ">", 30647))
		eval(answer(Evidence.DURATION, "<=", 3.1616))
		eval(answer(Evidence.CONN_STATE, "RSTO"))
		eval(answer(Evidence.ORIG_BYTES, "<=", 19))
		eval(answer(Evidence.DURATION, ">", 0.4998))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 34.61);
		insert(c);
end

rule "mra4_10"
	when
		eval(answer(Evidence.ID_ORIG_P, ">", 30647))
		eval(answer(Evidence.DURATION, "<=", 3.1616))
		eval(answer(Evidence.CONN_STATE, "S0"))
		eval(answer(Evidence.ORIG_BYTES, "<=", 19))
		eval(answer(Evidence.DURATION, ">", 0.4998))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 34.61);
		insert(c);
end

rule "mra4_11"
	when
		eval(answer(Evidence.ID_ORIG_P, ">", 30647))
		eval(answer(Evidence.DURATION, "<=", 3.1616))
		eval(answer(Evidence.CONN_STATE, "RSTO"))
		eval(answer(Evidence.ORIG_BYTES, "<=", 19))
		eval(answer(Evidence.DURATION, "<=", 0.4998))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 47.23);
		insert(c);
end

rule "mra4_12"
	when
		eval(answer(Evidence.ID_ORIG_P, ">", 30647))
		eval(answer(Evidence.DURATION, "<=", 3.1616))
		eval(answer(Evidence.CONN_STATE, "S0"))
		eval(answer(Evidence.ORIG_BYTES, "<=", 19))
		eval(answer(Evidence.DURATION, "<=", 0.4998))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 47.23);
		insert(c);
end

rule "mra4_13"
	when
		eval(answer(Evidence.ID_ORIG_P, "<=", 30647))
		eval(answer(Evidence.ID_RESP_P, ">", 45042))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 0.83);
		insert(c);
end

rule "mra4_14"
	when
		eval(answer(Evidence.ID_ORIG_P, "<=", 30647))
		eval(answer(Evidence.ID_RESP_P, "<=", 45042))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 0.00);
		insert(c);
end

// -----------------------------   48 - MIRAI

rule "mra1_1"
	when
		eval(answer(Evidence.RESP_PKTS, ">", 304))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 100);
        insert(c);
end

rule "mra1_2"
	when
		eval(answer(Evidence.RESP_PKTS, "<=", 304))
		eval(answer(Evidence.RESP_BYTES, ">", 82355))
		eval(answer(Evidence.ORIG_PKTS, ">", 138))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 21.69);
        insert(c);
end

rule "mra1_3"
	when
		eval(answer(Evidence.RESP_PKTS, "<=", 304))
		eval(answer(Evidence.RESP_BYTES, ">", 82355))
		eval(answer(Evidence.ORIG_PKTS, "<=", 138))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 14.55);
        insert(c);
end

rule "mra1_4"
	when
		eval(answer(Evidence.RESP_PKTS, "<=", 304))
		eval(answer(Evidence.RESP_BYTES, ">", 13208))
		eval(answer(Evidence.RESP_BYTES, "<=", 82355))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 9.41);
        insert(c);
end

rule "mra1_5"
	when
		eval(answer(Evidence.RESP_PKTS, "<=", 304))
		eval(answer(Evidence.RESP_BYTES, "<=", 13208))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 0.00);
        insert(c);
end

// -----------------------------   49 - MIRAI

rule "mra3_1"
	when
		eval(answer(Evidence.RESP_BYTES, ">", 179176))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 100.00);
        insert(c);
end

rule "mra3_2"
	when
		eval(answer(Evidence.RESP_BYTES, "<=", 179176))
		eval(answer(Evidence.RESP_BYTES, ">", 132319))
		eval(answer(Evidence.ORIG_BYTES, ">", 149))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 58.69);
        insert(c);
end

rule "mra3_3"
	when
		eval(answer(Evidence.RESP_BYTES, "<=", 179176))
		eval(answer(Evidence.RESP_BYTES, ">", 132319))
		eval(answer(Evidence.ORIG_BYTES, "<=", 149))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 44.18);
        insert(c);
end

rule "mra3_4"
	when
		eval(answer(Evidence.RESP_BYTES, ">", 60382))
		eval(answer(Evidence.RESP_BYTES, "<=", 132319))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 33.75);
        insert(c);
end

rule "mra3_5"
	when
		eval(answer(Evidence.RESP_BYTES, "<=", 60382))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 0.00);
        insert(c);
end

// -----------------------------   52 - MIRAI

rule "mra6_1"
	when
		eval(answer(Evidence.HISTORY, ">", 4))
		eval(answer(Evidence.ORIG_PKTS, ">", 81))
		eval(answer(Evidence.ID_ORIG_P, ">", 51677))
		eval(answer(Evidence.ORIG_BYTES, ">", 87))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 100.00);
        insert(c);
end

rule "mra6_2"
	when
		eval(answer(Evidence.HISTORY, ">", 4))
		eval(answer(Evidence.ORIG_PKTS, ">", 81))
		eval(answer(Evidence.ID_ORIG_P, ">", 51677))
		eval(answer(Evidence.ORIG_BYTES, "<=", 87))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 68.84);
        insert(c);
end

rule "mra6_3"
	when
		eval(answer(Evidence.HISTORY, ">", 4))
		eval(answer(Evidence.ORIG_PKTS, ">", 81))
		eval(answer(Evidence.ID_ORIG_P, "<=", 51677))
		eval(answer(Evidence.RESP_PKTS, ">", 109))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 51.30);
        insert(c);
end

rule "mra6_4"
	when
		eval(answer(Evidence.HISTORY, ">", 4))
		eval(answer(Evidence.ORIG_PKTS, ">", 81))
		eval(answer(Evidence.ID_ORIG_P, "<=", 51677))
		eval(answer(Evidence.RESP_PKTS, "<=", 109))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 38.77);
        insert(c);
end

rule "mra6_5"
	when
		eval(answer(Evidence.HISTORY, ">", 4))
		eval(answer(Evidence.ORIG_PKTS, "<=", 81))
		eval(answer(Evidence.SERVICE, "dns"))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 15.28);
        insert(c);
end

rule "mra6_6"
	when
		eval(answer(Evidence.HISTORY, ">", 4))
		eval(answer(Evidence.ORIG_PKTS, "<=", 81))
		not(eval(answer(Evidence.SERVICE, "dns")))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 6.08);
        insert(c);
end

rule "mra6_7"
	when
		eval(answer(Evidence.HISTORY, "<=", 4))
	then
		Conclusion c = new Conclusion(Conclusion.MIRAI, 0.00);
        insert(c);
end

// -----------------------------   60 - GAGFYT

rule "gft_1"
	when
		eval(answer(Evidence.ORIG_IP_BYTES, ">", 390632233))
		eval(answer(Evidence.ORIG_PKTS, ">", 19684999))
		eval(answer(Evidence.ID_ORIG_P, ">", 50420))
	then
		Conclusion c = new Conclusion(Conclusion.GAGFYT, 4.41);
        insert(c);
end

rule "gft_2"
	when
		eval(answer(Evidence.ORIG_IP_BYTES, ">", 390632233))
		eval(answer(Evidence.ORIG_PKTS, ">", 19684999))
		eval(answer(Evidence.ID_ORIG_P, "<=", 50420))
	then
		Conclusion c = new Conclusion(Conclusion.GAGFYT, 14.08);
        insert(c);
end

rule "gft_3"
	when
		eval(answer(Evidence.ORIG_IP_BYTES, ">", 390632233))
		eval(answer(Evidence.ORIG_PKTS, "<=", 19684999))
	then
		Conclusion c = new Conclusion(Conclusion.GAGFYT, 46.28);
        insert(c);
end

rule "gft_4"
	when
		eval(answer(Evidence.ORIG_IP_BYTES, "<=", 390632233))
		eval(answer(Evidence.ORIG_IP_BYTES, ">", 125909890))
	then
		Conclusion c = new Conclusion(Conclusion.GAGFYT, 8.34);
        insert(c);
end

rule "gft_5"
	when
		eval(answer(Evidence.ORIG_IP_BYTES, "<=", 125909890))
		eval(answer(Evidence.ID_RESP_P, ">", 55610))
		eval(answer(Evidence.ID_ORIG_P, ">", 22184))
	then
		Conclusion c = new Conclusion(Conclusion.GAGFYT, 0.34);
        insert(c);
end

rule "gft_6"
	when
		eval(answer(Evidence.ORIG_IP_BYTES, "<=", 125909890))
		eval(answer(Evidence.ID_RESP_P, ">", 55610))
		eval(answer(Evidence.ID_ORIG_P, "<=", 22184))
	then
		Conclusion c = new Conclusion(Conclusion.GAGFYT, 0.67);
        insert(c);
end

rule "gft_7"
	when
		eval(answer(Evidence.ORIG_IP_BYTES, "<=", 125909890))
		eval(answer(Evidence.ID_RESP_P, "<=", 55610))
	then
		Conclusion c = new Conclusion(Conclusion.GAGFYT, 0.01);
        insert(c);
end

query "evidence"(String ev, String v)
	e : Evidence( evidence == ev, value == v )
end

